plugins {
    id 'idea'
    id 'java'
    id 'maven-publish'
    id 'org.spongepowered.gradle.vanilla'
}
base {
    archivesName = "${mod_name}-common-${minecraft_version}"
}
minecraft {
    version(minecraft_version)
    if (file("src/main/resources/${mod_id}.aw").exists()) {
        accessWideners(file("src/main/resources/${mod_id}.aw"))
    }
}

repositories {
    mavenCentral()
    maven { url 'https://libs.azuredoom.com:4443/mods' }
    maven { url 'https://maven.blamejared.com' }
    maven { url 'https://api.modrinth.com/maven' }
    maven { url "https://cfa2.cursemaven.com" }
    maven { url "https://plugins.gradle.org/m2/" }
}

dependencies {
    compileOnly group:'org.spongepowered', name:'mixin', version:'0.8.5'
    compileOnly "mod.azure.azurelib:azurelib-neo-1.20.1:2.0.16"
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId base.archivesName.get()
            from components.java
        }
    }
    repositories {
        maven {
            url "file://" + System.getenv("local_maven")
        }
    }
}